import { useMemo } from 'react'

export default function useData() {
  const items = useMemo(
    () => [
      { id: 1, name: 'green' },
      { id: 2, name: 'blue' },
      { id: 3, name: 'red' },
      { id: 4, name: 'blue' },
      { id: 5, name: 'red' },
      { id: 6, name: 'green' },
      { id: 7, name: 'blue' },
      { id: 8, name: 'red' },
      { id: 9, name: 'green' },
      { id: 10, name: 'red' },
      { id: 11, name: 'green' },
      { id: 12, name: 'blue' },
      { id: 13, name: 'red' },
      { id: 14, name: 'green' },
      { id: 15, name: 'blue' },
      { id: 16, name: 'blue' },
      { id: 17, name: 'green' },
      { id: 18, name: 'red' },
      { id: 19, name: 'green' },
      { id: 20, name: 'red' },
      { id: 21, name: 'blue' },
      { id: 22, name: 'red' },
      { id: 23, name: 'blue' },
      { id: 24, name: 'green' },
      { id: 25, name: 'red' },
      { id: 26, name: 'green' },
      { id: 27, name: 'blue' },
      { id: 28, name: 'green' },
      { id: 29, name: 'red' },
      { id: 30, name: 'blue' },
      { id: 31, name: 'red' },
      { id: 32, name: 'blue' },
      { id: 33, name: 'green' },
      { id: 34, name: 'blue' },
      { id: 35, name: 'red' },
      { id: 36, name: 'green' },
      { id: 37, name: 'blue' },
      { id: 38, name: 'red' },
      { id: 39, name: 'green' },
      { id: 40, name: 'blue' },
      { id: 41, name: 'red' },
      { id: 42, name: 'green' },
      { id: 43, name: 'blue' },
      { id: 44, name: 'green' },
      { id: 45, name: 'red' },
      { id: 46, name: 'blue' },
      { id: 47, name: 'green' },
      { id: 48, name: 'red' },
      { id: 49, name: 'blue' },
      { id: 50, name: 'green' },
    ],
    []
  )

  return items
}
